- lib/3scale/api/client.rb
- lib/3scale/api/http_client.rb
- spec/api/client_spec.rb
- spec/integration/service_spec.rb
requires api to accept json as a request body
/cc @vdel26
> create service api call

- Gemfile
- Rakefile
- lib/3scale/api/client.rb
see http://www.rubydoc.info/github/3scale/3scale-api-ruby/master
> add basic yard doc

- lib/3scale/api/client.rb
- spec/api/client_spec.rb
- spec/integration/service_spec.rb
ability to list & create application plans
/cc @vdel26
> list & create application plans

- .travis.yml
- lib/3scale/api/client.rb
- lib/3scale/api/http_client.rb
- spec/api/client_spec.rb
- spec/api/http_client_spec.rb
- spec/integration/service_spec.rb
* Proxy Show
* Proxy Update
* Mapping Rules List
* Mapping Rule Show
* Mapping Rule Create
* Mapping Rule Update
* Mapping Rule Delete
/cc @vdel26
> proxy and mapping rules api

- CHANGELOG.md
- lib/3scale/api/client.rb
- spec/api/client_spec.rb
- spec/integration/account_spec.rb
closes #14
/cc @mayorova 
would be cool if you could try it before merging.
> implement more application endpoints

- CHANGELOG.md
- lib/3scale/api/client.rb
- lib/3scale/api/http_client.rb
- spec/api/client_spec.rb
- spec/api/http_client_spec.rb
- spec/integration/account_spec.rb
* customize application plan
* put in http client, closes #10
/cc @mayorova
> customize application plan

- .codeclimate.yml
- .rubocop.yml
- 3scale-api.gemspec
- Rakefile
- lib/3scale/api/client.rb
- lib/3scale/api/http_client.rb
- lib/3scale/api/version.rb
- spec/api/client_spec.rb
- spec/api/http_client_spec.rb
- spec/integration/account_spec.rb
- spec/integration/service_spec.rb
- spec/spec_helper.rb
* rubocop
* reek
* duplication
> enable codeclimate

- ThreeScaleRest.gemspec
- lib/three_scale_api/clients/account_user.rb
- lib/three_scale_api/clients/active_doc.rb
- lib/three_scale_api/clients/application.rb
- lib/three_scale_api/clients/application_key.rb
- lib/three_scale_api/clients/application_plan_limit.rb
- lib/three_scale_api/clients/default.rb
- lib/three_scale_api/clients/mapping_rule.rb
- lib/three_scale_api/clients/method.rb
- lib/three_scale_api/clients/metric.rb
- lib/three_scale_api/clients/plans.rb
- lib/three_scale_api/clients/provider.rb
- lib/three_scale_api/clients/proxy.rb
- lib/three_scale_api/clients/service.rb
- lib/three_scale_api/clients/settings.rb
- lib/three_scale_api/clients/webhook.rb
- lib/three_scale_api/resources/account.rb
- lib/three_scale_api/resources/application_key.rb
- lib/three_scale_api/resources/application_plan_limit.rb
- lib/three_scale_api/resources/default.rb
- lib/three_scale_api/resources/plans.rb
- lib/three_scale_api/resources/provider.rb
- lib/three_scale_api/resources/webhook.rb
- lib/three_scale_api/tools.rb
- spec/integration/active_doc_spec.rb
- spec/shared_examples.rb
Signed-off-by: Peter Stanko <pstanko@redhat.com>
> Lazy loading of the resource when using prepare or [] with id

- lib/three_scale_api/resources/application.rb
- spec/integration/application_spec.rb
Extracted from https://github.com/3scale/3scale-api-ruby/pull/25#issuecomment-311002335
> Application reference to service and application plan

- lib/three_scale_api/clients/proxy.rb
* Fixed log
* Renamed config_id to version for promote
Signed-off-by: Peter Stanko <pstanko@redhat.com>
> Proxy config

- lib/three_scale_api/tools.rb
Signed-off-by: Peter Stanko <pstanko@redhat.com>
> Updated logging messages

- .gitignore
- .rubocop.yml
- ThreeScaleRest.gemspec
- lib/three_scale_api/http_client.rb
- spec/shared_tests_config.rb
* Updated rubocop configuration
* Updated version of dependencies
* Updated gitignore
> Technical stuff

- CHANGELOG.md
- lib/3scale/api/version.rb
> release 0.1.6

- 3scale-api.gemspec
* fix homepage typo
* Include new authors
> Fix homepage and include authors from gemspec

- CHANGELOG.md
- lib/3scale/api/version.rb
> release 0.1.7

- lib/3scale/api/client.rb
- spec/api/client_spec.rb
Find account method to access 
```
GET /admin/api/accounts/find.json
```
endpoint.
Subtask to complete https://issues.jboss.org/browse/THREESCALE-1562 (implemented by https://github.com/3scale/porta/pull/379)
> Find account

- .travis.yml
- 3scale-api.gemspec
- spec/api/http_client_spec.rb
- spec/spec_helper.rb
Deprecate:
* 2.2.4
* 2.1.8
* jruby-9.0.5.0
* rbx-3.19
Enable for:
* 2.5.0
* 2.4.3
* 2.3.6
> Update ruby versions

- CHANGELOG.md
- lib/3scale/api/version.rb
Added:
- Find account method
- Activedocs methods
- PricingRules methods
- Policies methods
- Support for Ruby versions 2.5.0, 2.4.3, 2.3.6
> release 0.1.8

- lib/3scale/api/client.rb
- spec/api/client_spec.rb
OIDC Configuration operations
OIDC Configuration Show
> GET /admin/api/services/{service_id}/proxy/oidc_configuration.json
OIDC Configuration Update
> PATCH /admin/api/services/{service_id}/proxy/oidc_configuration.json
> oidc operations

- CHANGELOG.md
- lib/3scale/api/version.rb
**Added**
- Delete application plan customization
- Delete activedocs
- List accounts
- Delete account
- Delete application
- Show OIDC conf
- Update OIDC conf
**Fixed**
- Integration tests do the clean up
> release 0.1.9

- .travis.yml
ruby 2.3 is in EOL
Support ruby 2.6
> deprecate ruby 2.3, welcome ruby 2.6

- lib/3scale/api/client.rb
- spec/api/client_spec.rb
* proxy config list
* proxy config latest
> proxy config list and latest

- CHANGELOG.md
- lib/3scale/api/version.rb
- List limits per plan and metric
- Update app plan limit
- Operation to set application plan as default
> release 0.3.0

- lib/3scale/api/client.rb
- spec/api/client_spec.rb
This PR adds show and promote proxy_config API call methods.
It also fixes return content extraction for show latest and list
> Add show and promote proxy_config methods

- .rubocop.yml
- 3scale-api.gemspec
- lib/3scale/api/client.rb
- spec/api/client_spec.rb
- spec/integration/account_spec.rb
- spec/integration/service_spec.rb
- spec/shared_contexts.rb
[Rubocop](https://github.com/rubocop-hq/rubocop) offenses corrected
> rubocop formatter

- CHANGELOG.md
- lib/3scale/api/client.rb
- spec/api/client_spec.rb
Get information about the provider.
> added 'Provider Account Read' endpoint

- lib/3scale/api/client.rb
- spec/api/client_spec.rb
For some scripting work for a client I needed some additional methods regarding users and applications. I added the following methods to Client class:
- list_users
- create_user
- activate_user
- approve_account
- list_account_applications
- list_application_plans
- list_application_keys
- create_application_key
- accept_application
- suspend_application
- resume_application
> Added additional user and application methods

- lib/3scale/api/client.rb
- spec/api/client_spec.rb
> Application methods

- lib/3scale/api/client.rb
the format is `@param [T] name description`
> fix invalid documentation

- lib/3scale/api/client.rb
- spec/api/client_spec.rb
* Backends
* Backend Method
* Backend Metric
* Backend Mapping Rule
* Backend Usage
> backend endpoints

- CHANGELOG.md
- lib/3scale/api/version.rb
Signed-off-by: Eguzki Astiz Lezaun <eastizle@redhat.com>
> release 1.1.0

- lib/3scale/api/client.rb
- spec/api/client_spec.rb
* Service list endpoints supports query params
* Backend list endpoints supports query params
> Service and backend list endpoints support queryparams

- .circleci/config.yml
- .circleci/setup-rubygems.sh
Push to rubygems automatically when test pass and on tags
> automate rubygems push
